name: fla_custom
description: A flarum application by Flutter.

version: 1.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  core:
    ## for debug,use local library
    #path: ../core
    git:
      url: https://github.com/fluam/core.git
      ### To use the latest core version, please comment out'ref'
      #### and use flutter pub upgrade to update.
      ref: 0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true